embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/planet/planet.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"magick_ball_01\"\n"
  "  material: \"/builtins/materials/model.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/builtins/assets/images/logo/logo_256.png\"\n"
  "  }\n"
  "}\n"
  ""
}
