embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/planet/planet.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"moon\"\n"
  "  material: \"/materials/model.material\"\n"
  "  textures {\n"
  "    sampler: \"DATA_TEXTURE\"\n"
  "    texture: \"/illumination/textures/data.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"DIFFUSE_TEXTURE\"\n"
  "    texture: \"/assets/models/planet/moon_BaseColor.jpg\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"LIGHT_TEXTURE\"\n"
  "    texture: \"/illumination/textures/empty.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"NORMAL_TEXTURE\"\n"
  "    texture: \"/illumination/textures/empty.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"SPECULAR_TEXTURE\"\n"
  "    texture: \"/hyper_trails/textures/white.png\"\n"
  "  }\n"
  "}\n"
  ""
  position {
    z: -50.0
  }
}
