local rendy = require "rendy.rendy"

local factory_url
local function create_particle(pos)
	factory.create(factory_url, pos)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	factory_url = "#factory"
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then
		if action.pressed then
			local pos = rendy.screen_to_world(hash("/rendy"), vmath.vector3(action.screen_x, action.screen_y, 15))
			pos.z = 0
			pprint(pos)

			create_particle(pos)
		end
	end
end